# Change these first
owner: itbm-services # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: CulturalGo Platform
    url: https://culturalgo.com/plataform
  - name: Survey
    url: https://newsurvey.culturalgo.com/
  - name: Culture Audit
    url: https://culture04.culturalgo.com:8443/
  - name: SuccesGo
    url: https://success.culturalgo.com/
  - name: Leadergo!
    url: https://leadergo.org/
  - name: CGO Express!
    url:  https://cgoxgptw.culturalgo.com/
 
    
assignees:
   - itbm-services

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /monitoring
  logoUrl: https://app04.culturalgo.com/assetsCGO5/platform/logos/cgo.png
  name: Status CGO / ITBM
  introTitle: "**Status CGO** is the monitor of CulturalGo services"
  introMessage: This is a **real-time** view of the services. Monitor uptime every 5 minutes.
  navbar:
    - title: Status
      href: /
    - title: CulturalGo
      href: https://culturalgo.com/

# Upptime also supports notifications, assigning issues, and more

# Webhook notifications

# See https://upptime.js.org/docs/configuration
